export const TODOS_ADD = 'TODOS_ADD';
export const SET_COMPLETED = 'SET_COMPLETED';
export const TODOS_REMOVE = 'TODOS_REMOVE';
export const SET_ALL_COMPLETED = 'SET_ALL_COMPLETED';
export const TODOS_REMOVE_ALL_COMPLETED = 'TODOS_REMOVE_ALL_COMPLETED';